### ISSUE TITLE
Change retrunType for M365 report functions to Edm.Steam

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-metadata#79] opened 2021-04-30 00:13 UTC
The converted [OpenAPI document](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/openApiDocs/v1.0/Reports.yml#L3326) currently represents response type of most report functions as `application/json` instead of `application/octet-stream`. To solve this, we need to ensure that response types of functions bound to reportRoot are accurately represented in the converted OpenAPI. Without this, code generators won't be able to know how to properly handle responses.

#### Currently
This CSDL with the wrong return type:
![image](https://user-images.githubusercontent.com/7061532/115089355-e9e8e680-9ec6-11eb-928f-cc163f94b912.png)
![image](https://user-images.githubusercontent.com/7061532/115089908-413b8680-9ec8-11eb-9e86-4f75303c3ce3.png)

Gets converted to this in OpenAPI:
![image](https://user-images.githubusercontent.com/7061532/115088029-31ba3e80-9ec4-11eb-84a9-7da833767b20.png)

### Expected
For reports to function as described in [MS Graph docs](https://docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivitycounts?view=graph-rest-1.0#response), we need to ensure that they are described as shown below:
![image](https://user-images.githubusercontent.com/7061532/115088128-60d0b000-9ec4-11eb-8914-12dfba509f2d.png)

Related to https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/407
 
[AB#9223](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9223)

**Comment by joshtransient** [comment] 2021-12-09 13:06
Any updates to this yet?

**Comment by silijon** [comment] 2022-02-10 18:22
Also looking for an update on this. As far as we can tell, the entire Microsoft.Graph.Reports powershell sdk module is irretrievably broken until this is fixed.

**Comment by DanijelkMSFT** [comment] 2022-03-10 08:29
@silijon agree it would be great to see this fixed until then you may use this workaround with Peter provided me.
As it allows you to still use Graph Powershell und simply move forward as soon as the issue is fixed 

`Invoke-MgGraphRequest -Uri "https://graph.microsoft.com/beta/reports/getM365AppUserDetail(period='D7')/content" -OutputFilePath test.csv`

**Comment by irvinesunday** [comment] 2022-10-19 19:03
Resolved with https://github.com/microsoftgraph/msgraph-metadata/pull/213

**Closed by irvinesunday** 2022-10-19 19:03 UTC
